# Generated by Django 6.1.1 on 2026-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurfRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('phone_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=150)),
            ],
        ),
    ]
