# Generated by Django 6.1.1 on 2026-10-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turf_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf_booking.turf')),
            ],
        ),
    ]
